package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Audit generated by hbm2java
 */
public class Audit  implements java.io.Serializable {


     private int idaudit;
     private Usuario usuario;
     private Date fechaAudit;
     private String accion;
     private String tablaNombre;

    public Audit() {
    }

	
    public Audit(int idaudit, Usuario usuario) {
        this.idaudit = idaudit;
        this.usuario = usuario;
    }
    public Audit(int idaudit, Usuario usuario, Date fechaAudit, String accion, String tablaNombre) {
       this.idaudit = idaudit;
       this.usuario = usuario;
       this.fechaAudit = fechaAudit;
       this.accion = accion;
       this.tablaNombre = tablaNombre;
    }
   
    public int getIdaudit() {
        return this.idaudit;
    }
    
    public void setIdaudit(int idaudit) {
        this.idaudit = idaudit;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaAudit() {
        return this.fechaAudit;
    }
    
    public void setFechaAudit(Date fechaAudit) {
        this.fechaAudit = fechaAudit;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public String getTablaNombre() {
        return this.tablaNombre;
    }
    
    public void setTablaNombre(String tablaNombre) {
        this.tablaNombre = tablaNombre;
    }




}


