package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private String nombreTabla;
     private Integer id;
     private String descripcion;

    public Configuracion() {
    }

	
    public Configuracion(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }
    public Configuracion(String nombreTabla, Integer id) {
       this.nombreTabla = nombreTabla;
       this.id = id;
    }
   
	// <editor-fold defaultstate="collapsed" desc="Getters and Setters"> 
	
    public String getNombreTabla() {
        return this.nombreTabla;
    }
    
    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
	
	// </editor-fold>
	
}


