package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1



/**
 * Convenio generated by hbm2java
 */
public class Convenio  implements java.io.Serializable {


     private ConvenioId id;
     private Monto monto;
     private Reglabonificacion reglabonificacion;
     private Tipobonificacion tipobonificacion;
     private Unidad unidad;
     private Integer deudaTotal;
     private Boolean tieneBonificacion;
     private Integer cuotas;
     private Integer saldoInicial;
     private String descripcion;
     private Boolean activo;

    public Convenio() {
    }

	
    public Convenio(ConvenioId id, Monto monto, Reglabonificacion reglabonificacion, Tipobonificacion tipobonificacion, Unidad unidad) {
        this.id = id;
        this.monto = monto;
        this.reglabonificacion = reglabonificacion;
        this.tipobonificacion = tipobonificacion;
        this.unidad = unidad;
    }
    public Convenio(ConvenioId id, Monto monto, Reglabonificacion reglabonificacion, Tipobonificacion tipobonificacion, Unidad unidad, Integer deudaTotal, Boolean tieneBonificacion, Integer cuotas, Integer saldoInicial, String descripcion, Boolean activo) {
       this.id = id;
       this.monto = monto;
       this.reglabonificacion = reglabonificacion;
       this.tipobonificacion = tipobonificacion;
       this.unidad = unidad;
       this.deudaTotal = deudaTotal;
       this.tieneBonificacion = tieneBonificacion;
       this.cuotas = cuotas;
       this.saldoInicial = saldoInicial;
       this.descripcion = descripcion;
       this.activo = activo;
    }
   
    public ConvenioId getId() {
        return this.id;
    }
    
    public void setId(ConvenioId id) {
        this.id = id;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Reglabonificacion getReglabonificacion() {
        return this.reglabonificacion;
    }
    
    public void setReglabonificacion(Reglabonificacion reglabonificacion) {
        this.reglabonificacion = reglabonificacion;
    }
    public Tipobonificacion getTipobonificacion() {
        return this.tipobonificacion;
    }
    
    public void setTipobonificacion(Tipobonificacion tipobonificacion) {
        this.tipobonificacion = tipobonificacion;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getDeudaTotal() {
        return this.deudaTotal;
    }
    
    public void setDeudaTotal(Integer deudaTotal) {
        this.deudaTotal = deudaTotal;
    }
    public Boolean getTieneBonificacion() {
        return this.tieneBonificacion;
    }
    
    public void setTieneBonificacion(Boolean tieneBonificacion) {
        this.tieneBonificacion = tieneBonificacion;
    }
    public Integer getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Integer cuotas) {
        this.cuotas = cuotas;
    }
    public Integer getSaldoInicial() {
        return this.saldoInicial;
    }
    
    public void setSaldoInicial(Integer saldoInicial) {
        this.saldoInicial = saldoInicial;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


