package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1



/**
 * ConvenioId generated by hbm2java
 */
public class ConvenioId  implements java.io.Serializable {


     private int idconvenio;
     private int unidadIdUnidad;

    public ConvenioId() {
    }

    public ConvenioId(int idconvenio, int unidadIdUnidad) {
       this.idconvenio = idconvenio;
       this.unidadIdUnidad = unidadIdUnidad;
    }
   
    public int getIdconvenio() {
        return this.idconvenio;
    }
    
    public void setIdconvenio(int idconvenio) {
        this.idconvenio = idconvenio;
    }
    public int getUnidadIdUnidad() {
        return this.unidadIdUnidad;
    }
    
    public void setUnidadIdUnidad(int unidadIdUnidad) {
        this.unidadIdUnidad = unidadIdUnidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConvenioId) ) return false;
		 ConvenioId castOther = ( ConvenioId ) other; 
         
		 return (this.getIdconvenio()==castOther.getIdconvenio())
 && (this.getUnidadIdUnidad()==castOther.getUnidadIdUnidad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdconvenio();
         result = 37 * result + this.getUnidadIdUnidad();
         return result;
   }   


}


