package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1



/**
 * Cuotaconvenio generated by hbm2java
 */
public class Cuotaconvenio  implements java.io.Serializable {


     private CuotaconvenioId id;
     private Convenio convenio;
     private Monto monto;
     private Tipobonificacion tipobonificacion;
     private Integer numeroCuota;
     private String descripcion;
     private Boolean pago;

    public Cuotaconvenio() {
    }

	
    public Cuotaconvenio(CuotaconvenioId id, Convenio convenio, Monto monto, Tipobonificacion tipobonificacion) {
        this.id = id;
        this.convenio = convenio;
        this.monto = monto;
        this.tipobonificacion = tipobonificacion;
    }
    public Cuotaconvenio(CuotaconvenioId id, Convenio convenio, Monto monto, Tipobonificacion tipobonificacion, Integer numeroCuota, String descripcion, Boolean pago) {
       this.id = id;
       this.convenio = convenio;
       this.monto = monto;
       this.tipobonificacion = tipobonificacion;
       this.numeroCuota = numeroCuota;
       this.descripcion = descripcion;
       this.pago = pago;
    }
   
    public CuotaconvenioId getId() {
        return this.id;
    }
    
    public void setId(CuotaconvenioId id) {
        this.id = id;
    }
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Tipobonificacion getTipobonificacion() {
        return this.tipobonificacion;
    }
    
    public void setTipobonificacion(Tipobonificacion tipobonificacion) {
        this.tipobonificacion = tipobonificacion;
    }
    public Integer getNumeroCuota() {
        return this.numeroCuota;
    }
    
    public void setNumeroCuota(Integer numeroCuota) {
        this.numeroCuota = numeroCuota;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getPago() {
        return this.pago;
    }
    
    public void setPago(Boolean pago) {
        this.pago = pago;
    }




}


