package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idestado;
     private String nombre;
     private String descripcion;
     private Integer orden;
     private Set trabajos = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idestado) {
        this.idestado = idestado;
    }
    public Estado(int idestado, String nombre, String descripcion, Integer orden, Set trabajos) {
       this.idestado = idestado;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.orden = orden;
       this.trabajos = trabajos;
    }
   
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }




}


