package entities.persistence.entities;
// Generated 21-ene-2017 0:24:10 by Hibernate Tools 4.3.1



/**
 * Gastoscomunes generated by hbm2java
 */
public class Gastoscomunes  implements java.io.Serializable {


     private GastoscomunesId id;
     private Monto monto;
     private Unidad unidad;
     private Boolean isBonificacion;
     private Boolean isPago;
     private Integer monto_1;
     private Boolean activo;
     private String gastosComunescol;

    public Gastoscomunes() {
    }

	
    public Gastoscomunes(GastoscomunesId id, Monto monto, Unidad unidad, String gastosComunescol) {
        this.id = id;
        this.monto = monto;
        this.unidad = unidad;
        this.gastosComunescol = gastosComunescol;
    }
    public Gastoscomunes(GastoscomunesId id, Monto monto, Unidad unidad, Boolean isBonificacion, Boolean isPago, Integer monto_1, Boolean activo, String gastosComunescol) {
       this.id = id;
       this.monto = monto;
       this.unidad = unidad;
       this.isBonificacion = isBonificacion;
       this.isPago = isPago;
       this.monto_1 = monto_1;
       this.activo = activo;
       this.gastosComunescol = gastosComunescol;
    }
   
    public GastoscomunesId getId() {
        return this.id;
    }
    
    public void setId(GastoscomunesId id) {
        this.id = id;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Boolean getIsBonificacion() {
        return this.isBonificacion;
    }
    
    public void setIsBonificacion(Boolean isBonificacion) {
        this.isBonificacion = isBonificacion;
    }
    public Boolean getIsPago() {
        return this.isPago;
    }
    
    public void setIsPago(Boolean isPago) {
        this.isPago = isPago;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getGastosComunescol() {
        return this.gastosComunescol;
    }
    
    public void setGastosComunescol(String gastosComunescol) {
        this.gastosComunescol = gastosComunescol;
    }




}


