package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1



/**
 * Gastoscomunes generated by hbm2java
 */
public class Gastoscomunes  implements java.io.Serializable {


     private GastoscomunesId id;
     private Monto monto;
     private Unidad unidad;
     private Boolean isBonificacion;
     private Boolean isPago;
     private Integer monto_1;

    public Gastoscomunes() {
    }

	
    public Gastoscomunes(GastoscomunesId id, Monto monto, Unidad unidad) {
        this.id = id;
        this.monto = monto;
        this.unidad = unidad;
    }
    public Gastoscomunes(GastoscomunesId id, Monto monto, Unidad unidad, Boolean isBonificacion, Boolean isPago, Integer monto_1) {
       this.id = id;
       this.monto = monto;
       this.unidad = unidad;
       this.isBonificacion = isBonificacion;
       this.isPago = isPago;
       this.monto_1 = monto_1;
    }
   
    public GastoscomunesId getId() {
        return this.id;
    }
    
    public void setId(GastoscomunesId id) {
        this.id = id;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Boolean getIsBonificacion() {
        return this.isBonificacion;
    }
    
    public void setIsBonificacion(Boolean isBonificacion) {
        this.isBonificacion = isBonificacion;
    }
    public Boolean getIsPago() {
        return this.isPago;
    }
    
    public void setIsPago(Boolean isPago) {
        this.isPago = isPago;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }




}


