package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idgrupo;
     private String nombre;
     private String descripcion;
     private Set trabajos = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }
    public Grupo(int idgrupo, String nombre, String descripcion, Set trabajos) {
       this.idgrupo = idgrupo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.trabajos = trabajos;
    }
   
    public int getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }




}


