package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historialmonto generated by hbm2java
 */
public class Historialmonto  implements java.io.Serializable {


     private HistorialmontoId id;
     private Monto monto;
     private Date fechaActualizacion;
     private Integer valorPesos;
     private Boolean activo;

    public Historialmonto() {
    }

	
    public Historialmonto(HistorialmontoId id, Monto monto) {
        this.id = id;
        this.monto = monto;
    }
    public Historialmonto(HistorialmontoId id, Monto monto, Date fechaActualizacion, Integer valorPesos, Boolean activo) {
       this.id = id;
       this.monto = monto;
       this.fechaActualizacion = fechaActualizacion;
       this.valorPesos = valorPesos;
       this.activo = activo;
    }
   
	// <editor-fold defaultstate="collapsed" desc="Getters and Setters"> 
	
    public HistorialmontoId getId() {
        return this.id;
    }
    
    public void setId(HistorialmontoId id) {
        this.id = id;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Integer getValorPesos() {
        return this.valorPesos;
    }
    
    public void setValorPesos(Integer valorPesos) {
        this.valorPesos = valorPesos;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

	// </editor-fold>


}


