package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1



/**
 * HistorialmontoId generated by hbm2java
 */
public class HistorialmontoId  implements java.io.Serializable {


     private int idhistorialMonto;
     private int montoIdmonto;

    public HistorialmontoId() {
    }

    public HistorialmontoId(int idhistorialMonto, int montoIdmonto) {
       this.idhistorialMonto = idhistorialMonto;
       this.montoIdmonto = montoIdmonto;
    }
   
    public int getIdhistorialMonto() {
        return this.idhistorialMonto;
    }
    
    public void setIdhistorialMonto(int idhistorialMonto) {
        this.idhistorialMonto = idhistorialMonto;
    }
    public int getMontoIdmonto() {
        return this.montoIdmonto;
    }
    
    public void setMontoIdmonto(int montoIdmonto) {
        this.montoIdmonto = montoIdmonto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistorialmontoId) ) return false;
		 HistorialmontoId castOther = ( HistorialmontoId ) other; 
         
		 return (this.getIdhistorialMonto()==castOther.getIdhistorialMonto())
 && (this.getMontoIdmonto()==castOther.getMontoIdmonto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdhistorialMonto();
         result = 37 * result + this.getMontoIdmonto();
         return result;
   }   


}


