package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idmaterial;
     private String nombre;
     private String descripcion;
     private Integer cantidad;
     private Integer entrada;
     private Integer salida;
     private boolean activo;
     private Set listaprecioses = new HashSet(0);
     private Set trabajoxmaterials = new HashSet(0);

    public Material() {
    }

	
    public Material(int idmaterial, boolean activo) {
        this.idmaterial = idmaterial;
        this.activo = activo;
    }
    public Material(int idmaterial, String nombre, String descripcion, Integer cantidad, Integer entrada, Integer salida, boolean activo, Set listaprecioses, Set trabajoxmaterials) {
       this.idmaterial = idmaterial;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.entrada = entrada;
       this.salida = salida;
       this.activo = activo;
       this.listaprecioses = listaprecioses;
       this.trabajoxmaterials = trabajoxmaterials;
    }
   
	// <editor-fold defaultstate="collapsed" desc="Getters and Setters"> 
	
    public int getIdmaterial() {
        return this.idmaterial;
    }
    
    public void setIdmaterial(int idmaterial) {
        this.idmaterial = idmaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Integer entrada) {
        this.entrada = entrada;
    }
    public Integer getSalida() {
        return this.salida;
    }
    
    public void setSalida(Integer salida) {
        this.salida = salida;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getListaprecioses() {
        return this.listaprecioses;
    }
    
    public void setListaprecioses(Set listaprecioses) {
        this.listaprecioses = listaprecioses;
    }
    public Set getTrabajoxmaterials() {
        return this.trabajoxmaterials;
    }
    
    public void setTrabajoxmaterials(Set trabajoxmaterials) {
        this.trabajoxmaterials = trabajoxmaterials;
    }
	
	// </editor-fold>

    @Override
    public String toString() {
       return nombre;
    }

}