package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Monto generated by hbm2java
 */
public class Monto  implements java.io.Serializable {


     private int idmonto;
     private String tipoMonto;
     private Integer valorPesos;
     private Date fechaActualizacion;
     private Boolean activo;
     private Set otrosgastoses = new HashSet(0);
     private Set cuotaconvenios = new HashSet(0);
     private Set gastoscomuneses = new HashSet(0);
     private Set convenios = new HashSet(0);
     private Set historialmontos = new HashSet(0);

    public Monto() {
    }

	
    public Monto(int idmonto) {
        this.idmonto = idmonto;
    }
    public Monto(int idmonto, String tipoMonto, Integer valorPesos, Date fechaActualizacion, Boolean activo, Set otrosgastoses, Set cuotaconvenios, Set gastoscomuneses, Set convenios, Set historialmontos) {
       this.idmonto = idmonto;
       this.tipoMonto = tipoMonto;
       this.valorPesos = valorPesos;
       this.fechaActualizacion = fechaActualizacion;
       this.activo = activo;
       this.otrosgastoses = otrosgastoses;
       this.cuotaconvenios = cuotaconvenios;
       this.gastoscomuneses = gastoscomuneses;
       this.convenios = convenios;
       this.historialmontos = historialmontos;
    }
   
    public int getIdmonto() {
        return this.idmonto;
    }
    
    public void setIdmonto(int idmonto) {
        this.idmonto = idmonto;
    }
    public String getTipoMonto() {
        return this.tipoMonto;
    }
    
    public void setTipoMonto(String tipoMonto) {
        this.tipoMonto = tipoMonto;
    }
    public Integer getValorPesos() {
        return this.valorPesos;
    }
    
    public void setValorPesos(Integer valorPesos) {
        this.valorPesos = valorPesos;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getOtrosgastoses() {
        return this.otrosgastoses;
    }
    
    public void setOtrosgastoses(Set otrosgastoses) {
        this.otrosgastoses = otrosgastoses;
    }
    public Set getCuotaconvenios() {
        return this.cuotaconvenios;
    }
    
    public void setCuotaconvenios(Set cuotaconvenios) {
        this.cuotaconvenios = cuotaconvenios;
    }
    public Set getGastoscomuneses() {
        return this.gastoscomuneses;
    }
    
    public void setGastoscomuneses(Set gastoscomuneses) {
        this.gastoscomuneses = gastoscomuneses;
    }
    public Set getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set convenios) {
        this.convenios = convenios;
    }
    public Set getHistorialmontos() {
        return this.historialmontos;
    }
    
    public void setHistorialmontos(Set historialmontos) {
        this.historialmontos = historialmontos;
    }




}


