package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Otrosgastos generated by hbm2java
 */
public class Otrosgastos  implements java.io.Serializable {


     private OtrosgastosId id;
     private Concepto concepto;
     private Monto monto;
     private Unidad unidad;
     private Integer secuencia;
     private String descripcion;
     private Integer monto_1;
     private Date fecha;
     private Boolean pago;
     private boolean activo;

    public Otrosgastos() {
    }

	
    public Otrosgastos(OtrosgastosId id, Concepto concepto, Monto monto, Unidad unidad, boolean activo) {
        this.id = id;
        this.concepto = concepto;
        this.monto = monto;
        this.unidad = unidad;
        this.activo = activo;
    }
    public Otrosgastos(OtrosgastosId id, Concepto concepto, Monto monto, Unidad unidad, Integer secuencia, String descripcion, Integer monto_1, Date fecha, Boolean pago, boolean activo) {
       this.id = id;
       this.concepto = concepto;
       this.monto = monto;
       this.unidad = unidad;
       this.secuencia = secuencia;
       this.descripcion = descripcion;
       this.monto_1 = monto_1;
       this.fecha = fecha;
       this.pago = pago;
       this.activo = activo;
    }
   
    public OtrosgastosId getId() {
        return this.id;
    }
    
    public void setId(OtrosgastosId id) {
        this.id = id;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getPago() {
        return this.pago;
    }
    
    public void setPago(Boolean pago) {
        this.pago = pago;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


