package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1



/**
 * Permisosusuario generated by hbm2java
 */
public class Permisosusuario  implements java.io.Serializable {


     private String pagina;
     private Tipousuario tipousuario;
     private int permiso;

    public Permisosusuario() {
    }

    public Permisosusuario(String pagina, Tipousuario tipousuario, int permiso) {
       this.pagina = pagina;
       this.tipousuario = tipousuario;
       this.permiso = permiso;
    }
   
    public String getPagina() {
        return this.pagina;
    }
    
    public void setPagina(String pagina) {
        this.pagina = pagina;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public int getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }




}


