package entities.persistence.entities;
// Generated 26-oct-2017 20:25:54 by Hibernate Tools 4.3.1

/**
 * PermisosusuarioId generated by hbm2java
 */
public class PermisosusuarioId implements java.io.Serializable {

	private String pagina;
	private int tipousuarioId;

	public PermisosusuarioId() {
	}

	public PermisosusuarioId(String pagina, int tipousuarioId) {
		this.pagina = pagina;
		this.tipousuarioId = tipousuarioId;
	}

	// <editor-fold defaultstate="collapsed" desc="Getters and Setters"> 
	public String getPagina() {
		return this.pagina;
	}

	public void setPagina(String pagina) {
		this.pagina = pagina;
	}

	public int getTipousuarioId() {
		return this.tipousuarioId;
	}

	public void setTipousuarioId(int tipousuarioId) {
		this.tipousuarioId = tipousuarioId;
	}

	// </editor-fold>
	
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof PermisosusuarioId)) {
			return false;
		}
		PermisosusuarioId castOther = (PermisosusuarioId) other;

		return ((this.getPagina() == castOther.getPagina()) || (this.getPagina() != null && castOther.getPagina() != null && this.getPagina().equals(castOther.getPagina())))
			&& (this.getTipousuarioId() == castOther.getTipousuarioId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPagina() == null ? 0 : this.getPagina().hashCode());
		result = 37 * result + this.getTipousuarioId();
		return result;
	}

}
