package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico  implements java.io.Serializable {


     private int idTecnico;
     private String nombre;
     private String apellido;
     private String telefono;
     private String mail;
     private Integer calificacion;
     private Integer estado;
     private Date fechaInicioEstado;
     private Date fechaFinEstado;
     private Boolean activo;
     private Set historialtrabajos = new HashSet(0);

    public Tecnico() {
    }

	
    public Tecnico(int idTecnico) {
        this.idTecnico = idTecnico;
    }
    public Tecnico(int idTecnico, String nombre, String apellido, String telefono, String mail, Integer calificacion, Integer estado, Date fechaInicioEstado, Date fechaFinEstado, Boolean activo, Set historialtrabajos) {
       this.idTecnico = idTecnico;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.mail = mail;
       this.calificacion = calificacion;
       this.estado = estado;
       this.fechaInicioEstado = fechaInicioEstado;
       this.fechaFinEstado = fechaFinEstado;
       this.activo = activo;
       this.historialtrabajos = historialtrabajos;
    }
   
    public int getIdTecnico() {
        return this.idTecnico;
    }
    
    public void setIdTecnico(int idTecnico) {
        this.idTecnico = idTecnico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaInicioEstado() {
        return this.fechaInicioEstado;
    }
    
    public void setFechaInicioEstado(Date fechaInicioEstado) {
        this.fechaInicioEstado = fechaInicioEstado;
    }
    public Date getFechaFinEstado() {
        return this.fechaFinEstado;
    }
    
    public void setFechaFinEstado(Date fechaFinEstado) {
        this.fechaFinEstado = fechaFinEstado;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getHistorialtrabajos() {
        return this.historialtrabajos;
    }
    
    public void setHistorialtrabajos(Set historialtrabajos) {
        this.historialtrabajos = historialtrabajos;
    }

    @Override
    public String toString() {
        return nombre + " " + apellido;
    }  

}


