package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoduracion generated by hbm2java
 */
public class Tipoduracion  implements java.io.Serializable {


     private int idtipoDuracion;
     private String nombre;
     private Set trabajos = new HashSet(0);

    public Tipoduracion() {
    }

	
    public Tipoduracion(int idtipoDuracion) {
        this.idtipoDuracion = idtipoDuracion;
    }
    public Tipoduracion(int idtipoDuracion, String nombre, Set trabajos) {
       this.idtipoDuracion = idtipoDuracion;
       this.nombre = nombre;
       this.trabajos = trabajos;
    }
   
    public int getIdtipoDuracion() {
        return this.idtipoDuracion;
    }
    
    public void setIdtipoDuracion(int idtipoDuracion) {
        this.idtipoDuracion = idtipoDuracion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }




}


