package entities.persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipobonificacion generated by hbm2java
 */
public class Tipobonificacion  implements java.io.Serializable {


     private int idtipoBonificacion;
     private Integer tipoBonificacion;
     private Integer valor;
     private boolean activo;
     private Set convenios = new HashSet(0);

    public Tipobonificacion() {
    }

	
    public Tipobonificacion(int idtipoBonificacion, boolean activo) {
        this.idtipoBonificacion = idtipoBonificacion;
        this.activo = activo;
    }
    public Tipobonificacion(int idtipoBonificacion, Integer tipoBonificacion, Integer valor, boolean activo, Set convenios) {
       this.idtipoBonificacion = idtipoBonificacion;
       this.tipoBonificacion = tipoBonificacion;
       this.valor = valor;
       this.activo = activo;
       this.convenios = convenios;
    }
   
    public int getIdtipoBonificacion() {
        return this.idtipoBonificacion;
    }
    
    public void setIdtipoBonificacion(int idtipoBonificacion) {
        this.idtipoBonificacion = idtipoBonificacion;
    }
    public Integer getTipoBonificacion() {
        return this.tipoBonificacion;
    }
    
    public void setTipoBonificacion(Integer tipoBonificacion) {
        this.tipoBonificacion = tipoBonificacion;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set convenios) {
        this.convenios = convenios;
    }

    @Override
    public String toString() {
        return valor.toString();
    }




}


