package entities.persistence.entities;
// Generated 21-ene-2017 0:24:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipobonificacion generated by hbm2java
 */
public class Tipobonificacion  implements java.io.Serializable {


     private int idtipoBonificacion;
     private Integer tipoBonificacion;
     private Integer valor;
     private boolean activo;
     private Set cuotaconvenios = new HashSet(0);

    public Tipobonificacion() {
    }

	
    public Tipobonificacion(int idtipoBonificacion, boolean activo) {
        this.idtipoBonificacion = idtipoBonificacion;
        this.activo = activo;
    }
    public Tipobonificacion(int idtipoBonificacion, Integer tipoBonificacion, Integer valor, boolean activo, Set cuotaconvenios) {
       this.idtipoBonificacion = idtipoBonificacion;
       this.tipoBonificacion = tipoBonificacion;
       this.valor = valor;
       this.activo = activo;
       this.cuotaconvenios = cuotaconvenios;
    }
   
    public int getIdtipoBonificacion() {
        return this.idtipoBonificacion;
    }
    
    public void setIdtipoBonificacion(int idtipoBonificacion) {
        this.idtipoBonificacion = idtipoBonificacion;
    }
    public Integer getTipoBonificacion() {
        return this.tipoBonificacion;
    }
    
    public void setTipoBonificacion(Integer tipoBonificacion) {
        this.tipoBonificacion = tipoBonificacion;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getCuotaconvenios() {
        return this.cuotaconvenios;
    }
    
    public void setCuotaconvenios(Set cuotaconvenios) {
        this.cuotaconvenios = cuotaconvenios;
    }




}


