package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipobonificacion generated by hbm2java
 */
public class Tipobonificacion  implements java.io.Serializable {


     private int idtipoBonificacion;
     private Integer tipoBonificacion;
     private Integer valor;
     private Set convenios = new HashSet(0);

    public Tipobonificacion() {
    }

	
    public Tipobonificacion(int idtipoBonificacion) {
        this.idtipoBonificacion = idtipoBonificacion;
    }
    public Tipobonificacion(int idtipoBonificacion, Integer tipoBonificacion, Integer valor, Set convenios) {
       this.idtipoBonificacion = idtipoBonificacion;
       this.tipoBonificacion = tipoBonificacion;
       this.valor = valor;
       this.convenios = convenios;
    }
   
    public int getIdtipoBonificacion() {
        return this.idtipoBonificacion;
    }
    
    public void setIdtipoBonificacion(int idtipoBonificacion) {
        this.idtipoBonificacion = idtipoBonificacion;
    }
    public Integer getTipoBonificacion() {
        return this.tipoBonificacion;
    }
    
    public void setTipoBonificacion(Integer tipoBonificacion) {
        this.tipoBonificacion = tipoBonificacion;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public Set getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set convenios) {
        this.convenios = convenios;
    }




}


