package entities.persistence.entities;
// Generated 24-ene-2017 23:29:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trabajo generated by hbm2java
 */
public class Trabajo  implements java.io.Serializable {


     private int idTrabajo;
     private Estado estado;
     private Grupo grupo;
     private Tipoduracion tipoduracion;
     private Unidad unidad;
     private Urgencia urgencia;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaVisita;
     private Integer calificacion;
     private Integer duracionEstimada;
     private Integer duracionReal;
     private byte activo;
     private Trabajoxmaterial trabajoxmaterial;
     private Set historialtrabajos = new HashSet(0);

    public Trabajo() {
    }

	
    public Trabajo(int idTrabajo, Estado estado, Grupo grupo, Tipoduracion tipoduracion, Unidad unidad, Urgencia urgencia, byte activo) {
        this.idTrabajo = idTrabajo;
        this.estado = estado;
        this.grupo = grupo;
        this.tipoduracion = tipoduracion;
        this.unidad = unidad;
        this.urgencia = urgencia;
        this.activo = activo;
    }
    public Trabajo(int idTrabajo, Estado estado, Grupo grupo, Tipoduracion tipoduracion, Unidad unidad, Urgencia urgencia, String descripcion, Date fechaCreacion, Date fechaVisita, Integer calificacion, Integer duracionEstimada, Integer duracionReal, byte activo, Trabajoxmaterial trabajoxmaterial, Set historialtrabajos) {
       this.idTrabajo = idTrabajo;
       this.estado = estado;
       this.grupo = grupo;
       this.tipoduracion = tipoduracion;
       this.unidad = unidad;
       this.urgencia = urgencia;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaVisita = fechaVisita;
       this.calificacion = calificacion;
       this.duracionEstimada = duracionEstimada;
       this.duracionReal = duracionReal;
       this.activo = activo;
       this.trabajoxmaterial = trabajoxmaterial;
       this.historialtrabajos = historialtrabajos;
    }
   
    public int getIdTrabajo() {
        return this.idTrabajo;
    }
    
    public void setIdTrabajo(int idTrabajo) {
        this.idTrabajo = idTrabajo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Tipoduracion getTipoduracion() {
        return this.tipoduracion;
    }
    
    public void setTipoduracion(Tipoduracion tipoduracion) {
        this.tipoduracion = tipoduracion;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Urgencia getUrgencia() {
        return this.urgencia;
    }
    
    public void setUrgencia(Urgencia urgencia) {
        this.urgencia = urgencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaVisita() {
        return this.fechaVisita;
    }
    
    public void setFechaVisita(Date fechaVisita) {
        this.fechaVisita = fechaVisita;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Integer getDuracionEstimada() {
        return this.duracionEstimada;
    }
    
    public void setDuracionEstimada(Integer duracionEstimada) {
        this.duracionEstimada = duracionEstimada;
    }
    public Integer getDuracionReal() {
        return this.duracionReal;
    }
    
    public void setDuracionReal(Integer duracionReal) {
        this.duracionReal = duracionReal;
    }
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }
    public Trabajoxmaterial getTrabajoxmaterial() {
        return this.trabajoxmaterial;
    }
    
    public void setTrabajoxmaterial(Trabajoxmaterial trabajoxmaterial) {
        this.trabajoxmaterial = trabajoxmaterial;
    }
    public Set getHistorialtrabajos() {
        return this.historialtrabajos;
    }
    
    public void setHistorialtrabajos(Set historialtrabajos) {
        this.historialtrabajos = historialtrabajos;
    }




}


