package entities.persistence.entities;
// Generated 21-ene-2017 0:24:10 by Hibernate Tools 4.3.1



/**
 * Trabajoxmaterial generated by hbm2java
 */
public class Trabajoxmaterial  implements java.io.Serializable {


     private int trabajoIdTrabajo;
     private Material material;
     private Trabajo trabajo;
     private Integer cantidad;

    public Trabajoxmaterial() {
    }

	
    public Trabajoxmaterial(Material material, Trabajo trabajo) {
        this.material = material;
        this.trabajo = trabajo;
    }
    public Trabajoxmaterial(Material material, Trabajo trabajo, Integer cantidad) {
       this.material = material;
       this.trabajo = trabajo;
       this.cantidad = cantidad;
    }
   
    public int getTrabajoIdTrabajo() {
        return this.trabajoIdTrabajo;
    }
    
    public void setTrabajoIdTrabajo(int trabajoIdTrabajo) {
        this.trabajoIdTrabajo = trabajoIdTrabajo;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Trabajo getTrabajo() {
        return this.trabajo;
    }
    
    public void setTrabajo(Trabajo trabajo) {
        this.trabajo = trabajo;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


