package entities.persistence.entities;
// Generated 20-ene-2017 21:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Urgencia generated by hbm2java
 */
public class Urgencia  implements java.io.Serializable {


     private int idurgencia;
     private String nombre;
     private String descripcion;
     private Set trabajos = new HashSet(0);

    public Urgencia() {
    }

	
    public Urgencia(int idurgencia) {
        this.idurgencia = idurgencia;
    }
    public Urgencia(int idurgencia, String nombre, String descripcion, Set trabajos) {
       this.idurgencia = idurgencia;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.trabajos = trabajos;
    }
   
    public int getIdurgencia() {
        return this.idurgencia;
    }
    
    public void setIdurgencia(int idurgencia) {
        this.idurgencia = idurgencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }




}


